name: Bump version

on:
  push:
    branches: [ master ]

env:
  node_version: 18

concurrency:
  group: release-actions

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Bump version
        run: sh ./.github/scripts/bump-version.sh
