name: Integration Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    environment:
      name: Test report
      url: ${{ steps.deploy.outputs.url }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Browsers
      run: npx playwright install chromium --with-deps
    - name: Build
      run: npm run build
    - name: Test
      run: xvfb-run npm run test:e2e
    - name: Deploy report
      id: deploy
      if: always()
      run: sh ./.github/scripts/deploy-report.sh
