name: Release

on:
  push:
    tags:
      - "**"
  workflow_run:
    workflows: [ "Bump version" ]
    types:
      - completed

env:
  node_version: 18

concurrency:
  group: release-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Get latest version
        id: get_version
        run: |
          echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Archive
        run: zip -r ../Chiller-${{ env.LATEST_TAG }}.zip *
        working-directory: dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: Chiller-${{ env.LATEST_TAG }}.zip
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get latest version
        id: get_version
        run: |
          echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Chiller-${{ env.LATEST_TAG }}.zip
          tag_name: ${{ env.LATEST_TAG }}
